#!/bin/sh
# =============================================================================
# Call of Duty 1 (v1.1) Dedicated Server - Entrypoint
# https://github.com/mmBesar/cod-container
#
# Responsibilities:
#   1. Verify /server/main/ is mounted and contains the required game files
#   2. Generate /server/codam/server.cfg from env vars (if no override exists)
#   3. Drop privileges to the UID:GID the container was started with (gosu)
#   4. Launch cod_lnxded with CoDExtended via LD_PRELOAD
# =============================================================================
set -e

log()  { printf '[entrypoint] %s\n' "$*"; }
die()  { printf '[entrypoint] FATAL: %s\n' "$*" >&2; exit 1; }

# =============================================================================
# Defaults - all overridable via environment variables
# =============================================================================

SERVER_HOSTNAME="${SERVER_HOSTNAME:-CoD1 Docker Server}"
SERVER_PASSWORD="${SERVER_PASSWORD:-}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
MOTD="${MOTD:-}"

SERVER_PORT="${SERVER_PORT:-28960}"
if [ -z "${SERVER_IP:-}" ]; then
    SERVER_IP="$(hostname -i | awk '{print $1}')"
    log "SERVER_IP not set, auto-detected: ${SERVER_IP}"
fi

GAMETYPE="${GAMETYPE:-tdm}"
MAX_CLIENTS="${MAX_CLIENTS:-16}"
SV_PURE="${SV_PURE:-0}"
FRIENDLY_FIRE="${FRIENDLY_FIRE:-0}"
SCORE_LIMIT="${SCORE_LIMIT:-100}"
TIME_LIMIT="${TIME_LIMIT:-30}"
ROUND_LIMIT="${ROUND_LIMIT:-0}"
ALLOW_VOTE="${ALLOW_VOTE:-0}"

START_MAP="${START_MAP:-mp_harbor}"
MAP_ROTATION="${MAP_ROTATION:-}"

X_AUTHORIZE="${X_AUTHORIZE:-0}"
X_DEADCHAT="${X_DEADCHAT:-0}"
X_NOPBOTS="${X_NOPBOTS:-1}"
X_SPECTATOR_NOCLIP="${X_SPECTATOR_NOCLIP:-0}"
SV_FAST_DOWNLOAD="${SV_FAST_DOWNLOAD:-1}"

SV_MASTER="${SV_MASTER:-master.cod.pm}"

BOTS_ENABLED="${BOTS_ENABLED:-false}"
BOTS_COUNT="${BOTS_COUNT:-4}"
BOTS_TEAM="${BOTS_TEAM:-autoassign}"
BOTS_DIFFICULTY="${BOTS_DIFFICULTY:-5}"

SV_FPS="${SV_FPS:-20}"
EXTRA_ARGS="${EXTRA_ARGS:-}"

# =============================================================================
# Step 1 - Verify /server/main/ is mounted and has required game files
#
# The user must mount their CoD1 main/ folder here. Without pak0.pk3 and
# game.mp.i386.so the server cannot start. We fail fast with a clear message
# rather than letting the engine produce a cryptic error.
# =============================================================================
log "Verifying /server/main/ ..."

[ -d "/server/main" ] \
    || die "/server/main is not mounted. Mount your CoD1 main/ folder here."

[ -f "/server/main/pak0.pk3" ] \
    || die "pak0.pk3 not found in /server/main/. Mount your CoD1 main/ folder."

[ -f "/server/main/game.mp.i386.so" ] \
    || die "game.mp.i386.so not found in /server/main/. Mount your CoD1 main/ folder."

[ -f "/server/main/localized_english_pak0.pk3" ] \
    || die "localized_english_pak0.pk3 not found in /server/main/. Mount your CoD1 main/ folder."

log "Game files verified OK."

# =============================================================================
# Step 2 - Config: use override or generate from env vars
#
# Config lives in /server/codam/ so the engine finds it via fs_game codam.
# If user drops a server.cfg in /server/config/ we symlink it in and skip
# generation entirely.
# =============================================================================
OVERRIDE_CFG="/server/config/server.cfg"
GENERATED_CFG="/server/codam/server.cfg"

if [ -f "$OVERRIDE_CFG" ]; then
    log "Found ${OVERRIDE_CFG} - using hand-crafted config, skipping generation."
    ln -sf "$OVERRIDE_CFG" "$GENERATED_CFG"
else
    log "Generating ${GENERATED_CFG} from env vars ..."

    # Build sv_mapRotation string
    # Format: "gametype <gt> map <map> gametype <gt> map <map> ..."
    if [ -n "$MAP_ROTATION" ]; then
        ROTATION_STRING=""
        for m in $MAP_ROTATION; do
            ROTATION_STRING="${ROTATION_STRING}gametype ${GAMETYPE} map ${m} "
        done
        ROTATION_STRING="${ROTATION_STRING% }"
    else
        ROTATION_STRING="gametype ${GAMETYPE} map ${START_MAP}"
    fi

    cat > "$GENERATED_CFG" << EOF
// =============================================================================
// server.cfg - auto-generated by docker-entrypoint.sh
// To use your own config, mount it at /server/config/server.cfg
// =============================================================================

// --- Server identity ---------------------------------------------------------
set sv_hostname         "${SERVER_HOSTNAME}"
set scr_motd            "${MOTD}"
set g_password          "${SERVER_PASSWORD}"
set rconpassword        "${RCON_PASSWORD}"

// --- Server options ----------------------------------------------------------
set sv_maxclients       "${MAX_CLIENTS}"
set sv_pure             "${SV_PURE}"
set sv_fps              "${SV_FPS}"
set sv_floodprotect     "1"
set sv_allowanonymous   "0"
set sv_cheats           "0"
set sv_allowdownload    "0"
set sv_privateclients   "0"
set sv_privatepassword  ""

// --- Masterserver ------------------------------------------------------------
set sv_master1          "master.cod.pm"
set sv_master2          "${SV_MASTER}"

// --- Gametype ----------------------------------------------------------------
set g_gametype          "${GAMETYPE}"
set g_allowvote         "${ALLOW_VOTE}"
set scr_allow_vote      "${ALLOW_VOTE}"
set scr_friendlyfire    "${FRIENDLY_FIRE}"
set scr_forcerespawn    "0"
set scr_drawfriend      "0"

// --- Per-gametype limits -----------------------------------------------------
set scr_dm_scorelimit   "${SCORE_LIMIT}"
set scr_dm_timelimit    "${TIME_LIMIT}"
set scr_tdm_scorelimit  "${SCORE_LIMIT}"
set scr_tdm_timelimit   "${TIME_LIMIT}"
set scr_bel_scorelimit  "${SCORE_LIMIT}"
set scr_bel_timelimit   "${TIME_LIMIT}"
set scr_sd_scorelimit   "${SCORE_LIMIT}"
set scr_sd_timelimit    "${TIME_LIMIT}"
set scr_sd_roundlimit   "${ROUND_LIMIT}"
set scr_re_scorelimit   "${SCORE_LIMIT}"
set scr_re_timelimit    "${TIME_LIMIT}"
set scr_re_roundlimit   "${ROUND_LIMIT}"

// --- Weapons (all enabled by default) ----------------------------------------
set scr_allow_m1carbine     "1"
set scr_allow_m1garand      "1"
set scr_allow_enfield       "1"
set scr_allow_bar           "1"
set scr_allow_bren          "1"
set scr_allow_mp40          "1"
set scr_allow_mp44          "1"
set scr_allow_sten          "1"
set scr_allow_ppsh          "1"
set scr_allow_fg42          "1"
set scr_allow_thompson      "1"
set scr_allow_panzerfaust   "1"
set scr_allow_springfield   "1"
set scr_allow_kar98ksniper  "1"
set scr_allow_nagantsniper  "1"
set scr_allow_kar98k        "1"
set scr_allow_nagant        "1"
set scr_allow_mg42          "1"

// --- CoDExtended CVARs -------------------------------------------------------
set x_authorize             "${X_AUTHORIZE}"
set x_deadchat              "${X_DEADCHAT}"
set x_nopbots               "${X_NOPBOTS}"
set x_spectator_noclip      "${X_SPECTATOR_NOCLIP}"
set sv_fastDownload         "${SV_FAST_DOWNLOAD}"

// --- Logging -----------------------------------------------------------------
set g_log                   "games_mp.log"
set g_logsync               "0"
set logfile                 "1"

// --- Map rotation ------------------------------------------------------------
set sv_mapRotation          "${ROTATION_STRING}"

// --- Execute CoDaM configs ---------------------------------------------------
exec CoDaM.cfg
exec CoDaM_HamGoodies.cfg

EOF
    log "Config generated at ${GENERATED_CFG}"
fi

# =============================================================================
# Step 3 - Bots note
# =============================================================================
if [ "$BOTS_ENABLED" = "true" ]; then
    log "Bots enabled: ${BOTS_COUNT} bots, team=${BOTS_TEAM}, difficulty=${BOTS_DIFFICULTY}"
    log "NOTE: MeatBot requires 'addbot' commands after server start."
    log "      Use rcon to issue: rcon addbot ${BOTS_TEAM}"
fi

# =============================================================================
# Step 4 - Build the server launch command
#
# fs_basepath /server  - where cod_lnxded and codextended.so live
# fs_homepath /server  - where the server writes runtime files
# fs_game codam        - tells the engine to load /server/codam/ as the mod
#                        this is where server.cfg and CoDaM pk3s live
# =============================================================================
log "Starting CoD1 server on ${SERVER_IP}:${SERVER_PORT} ..."
log "  Gametype    : ${GAMETYPE}"
log "  Max players : ${MAX_CLIENTS}"
log "  Start map   : ${START_MAP}"

exec gosu "$(id -u):$(id -g)" \
    env LD_PRELOAD=/server/codextended.so \
    /server/cod_lnxded \
        +set fs_basepath /server \
        +set fs_homepath /server \
        +set fs_game     codam \
        +set net_ip      "${SERVER_IP}" \
        +set net_port    "${SERVER_PORT}" \
        +set dedicated   1 \
        +exec            server.cfg \
        +map             "${START_MAP}" \
        ${EXTRA_ARGS} \
    < /dev/null
